### PR TITLE
Rerun notebooks

### PR DESCRIPTION
**Pull request by SergioMDCB**
# Description

This PR updates all the documentation notebooks to the latest mvg version (v0.12.2). Text on documentation is updated to clarify some confusing aspects, improve display of itemize lists and headings under each notebook. Furthermore, the say_hello function is updated to display only api info and a pandas warning on trying to update an original dataframe is removed.

New dependencies: (Added to requirements_*.txt)

Fixes # (potential issues that are fixed by this PR)

## Type of Change

- [X] Bug fix (non-breaking change which fixes an issue -> bump patch)
- [ ] New feature (non-breaking change which adds functionality -> bump minor version)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected -> bump major version)
- [X] Documentation Update
- [ ] CI/CD workflows Update

## Checklist

- [ ] I have added tests that prove that my fix/feature works
- [x] Linters pass locally and I have followed PEP8 code style
- [ ] New and existing tests pass locally
- [X] I have updated the documentation if needed
- [ ] I have commented hard-to-understand areas in the code

## Requirements

- [X] I have updated the MVG version

### CODE REVIEW

**Comment by vnadhan** [comment]
@SergioMDCB "a pandas warning on trying to update an original dataframe is removed" - was this warning due to some code in MVG or in the backend?

**Comment by vnadhan** [comment]
image
The results of ModeID actually contains four lists and two dictionaries. The first dictionary is named `mode_info` and the second is `mode_probabilities`. Shoudlnt we document about the second dict as well ?

**Comment by vnadhan** [comment]
> > 
> 
> @vnadhan It was due to some code in MVG. In particular, it relates within the file "analysis.py" to the function "_add_datetime_df". Before disabling the warning, I tried passing a copy(), skipping using the dt_col variable and mixing both

Ok, I will check it out. I think we should not use this warning disabler as that will likely hide warnings related to outdated pandas syntax.

**Comment by SergioMDCB** [comment]
> image The results of ModeID actually contains four lists and two dictionaries. The first dictionary is named `mode_info` and the second is `mode_probabilities`. Shoudlnt we document about the second dict as well ?

@vnadhan got catch, I had updated the description on the notebook to explain these results

**Review by vnadhan — APPROVED** [review]

**Comment by vnadhan** [comment]
Good work @SergioMDCB !!

**Review by vnadhan — APPROVED** [review]

**Pull request merged**
